#!/usr/bin/env bash
# Tạo ios/Flutter/Signing.xcconfig cho free Personal Team signing.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SIGNING="$ROOT/ios/Flutter/Signing.xcconfig"

echo "══ Setup iOS signing (free Apple ID) ══"
echo ""

# Thử lấy Team ID từ certificate đã có
detect_team() {
  security find-identity -v -p codesigning 2>/dev/null | \
    grep "Apple Development" | head -1 | \
    sed -n 's/.*(\([A-Z0-9]\{10\}\)).*/\1/p' || true
}

HAS_CERT=false
if security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"; then
  HAS_CERT=true
  echo "✓ Đã có Apple Development certificate"
else
  echo "⚠ Chưa có certificate — cần mở Xcode một lần:"
  echo "  1. Xcode > Settings > Accounts > + Apple ID"
  echo "  2. open ios/Runner.xcworkspace"
  echo "  3. Runner > Signing & Capabilities > chọn Personal Team"
  echo "  4. Cắm iPad USB (Trust) để đăng ký thiết bị"
  echo ""
  read -r -p "Mở Xcode ngay? [Y/n] " OPEN_XCODE
  if [[ "${OPEN_XCODE:-Y}" != "n" && "${OPEN_XCODE:-Y}" != "N" ]]; then
    open "$ROOT/ios/Runner.xcworkspace"
  fi
  echo ""
  echo "Sau khi chọn Team trong Xcode, chạy lại script này."
  echo ""
fi

DEFAULT_TEAM="${DEVELOPMENT_TEAM:-$(detect_team)}"
DEFAULT_BUNDLE="${BUNDLE_ID:-com.tuchi.tuchi}"

if [[ -n "$DEFAULT_TEAM" ]]; then
  echo "Team ID phát hiện: $DEFAULT_TEAM"
else
  echo "Team ID: lấy tại Xcode > Settings > Accounts > [Apple ID] > Team ID (10 ký tự)"
fi
echo ""

read -r -p "Team ID [$DEFAULT_TEAM]: " TEAM
TEAM="${TEAM:-$DEFAULT_TEAM}"
if [[ -z "$TEAM" || ${#TEAM} -ne 10 ]]; then
  echo "❌ Team ID phải đúng 10 ký tự"
  exit 1
fi

read -r -p "Bundle ID (unique) [$DEFAULT_BUNDLE]: " BUNDLE
BUNDLE="${BUNDLE:-$DEFAULT_BUNDLE}"

cat > "$SIGNING" <<EOF
// Generated by setup_ios_signing.sh — không commit (gitignored)
DEVELOPMENT_TEAM = $TEAM
PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE
CODE_SIGN_STYLE = Automatic
EOF

echo ""
echo "✓ Đã tạo: ios/Flutter/Signing.xcconfig"
echo "  DEVELOPMENT_TEAM = $TEAM"
echo "  PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE"
echo ""

if [[ "$HAS_CERT" == "false" ]]; then
  echo "→ Quay lại Xcode, chọn Team $TEAM, build thử 1 lần (⌘R với iPad cắm sẵn)"
  echo "→ Rồi chạy: ./scripts/build_ipa_ac.sh"
else
  echo "→ Chạy: ./scripts/build_ipa_ac.sh"
fi
